import "./globals.css";
import { Inter } from "next/font/google";
import { LanguageProvider } from "@/context/LanguageContext";


const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Mounia Mikou L'avocate de votre expatriation",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <LanguageProvider>

        <body className={inter.className}>{children}</body>
   
      </LanguageProvider>
    </html>
  );
}
