
import "./globals.css";

import { LanguageProvider } from "@/context/LanguageContext";





export const metadata = {
  title: "Mounia Mikou L'avocate de votre expatriation",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <LanguageProvider>

        <body>{children}</body>

      </LanguageProvider>
    </html>
  );
}
